version: '3'

services:

  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APACHE_CONFIG_PATH_HOST}:${APACHE_CONFIG_PATH_CONTAINER}
    ports:
      - 80:80
    working_dir: ${APP_PATH_CONTAINER}
    restart: always
  
  mysql: 
    image: mysql:latest
    restart: always
    ports:
          - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

  composer:
    image: composer:latest
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer i